[build]
  base = "web"
  publish = "dist"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "20"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# SPA fallback
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200